#!/bin/bash

bat=$(acpi | grep -o "[[:digit:]]*%")
chr=$(acpi | grep -o "Charging")
charge=$(cat /sys/class/power_supply/BAT0/capacity)

[ "$chr" == "Charging" ] && echo "  $bat" || echo "   $bat"

if [ "$charge" -le 15 ]; then
  notify-send -u critical "Low Battery!";
fi
sleep 1m;
